### ISSUE TITLE
调用`startScanAndConnect`时当扫描不到任何设备会发生崩溃

### ISSUE THREAD

**Issue by martinchengs** [buhuiming/BleCore#28]
```kotlin
java.lang.NullPointerException
                                                                      	at com.bhm.ble.request.base.BleRequestImp$startScanAndConnect$1.invokeSuspend(BleRequestImp.kt:168)
                                                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                      	at android.os.Handler.handleCallback(Handler.java:942)
                                                                      	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      	at android.os.Looper.loopOnce(Looper.java:210)
                                                                      	at android.os.Looper.loop(Looper.java:299)
                                                                      	at android.app.ActivityThread.main(ActivityThread.java:8261)
                                                                      	at java.lang.reflect.Method.invoke(Native Method)
                                                                      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                      	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bdbbac5, Dispatchers.Main]
```

**Comment by buhuiming** [comment]
已修复，v1.9.9
